Extension { #name : #Number }

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> AED [
	"United Arab Emirates dirham"
	
	^self asAmountInCurrency: #'AED' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> AFN [
	"Afghan afghani"
	
	^self asAmountInCurrency: #'AFN' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> ALL [
	"Albanian lek"
	
	^self asAmountInCurrency: #'ALL' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> AMD [
	"Armenian dram"
	
	^self asAmountInCurrency: #'AMD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> ANG [
	"Netherlands Antillean guilder"
	
	^self asAmountInCurrency: #'ANG' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> AOA [
	"Angolan kwanza"
	
	^self asAmountInCurrency: #'AOA' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> ARS [
	"Argentine peso"
	
	^self asAmountInCurrency: #'ARS' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> AUD [
	"Australian dollar"
	
	^self asAmountInCurrency: #'AUD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> AWG [
	"Aruban florin"
	
	^self asAmountInCurrency: #'AWG' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> AZN [
	"Azerbaijani manat"
	
	^self asAmountInCurrency: #'AZN' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BAM [
	"Bosnia and Herzegovina convertible mark"
	
	^self asAmountInCurrency: #'BAM' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BBD [
	"Barbados dollar"
	
	^self asAmountInCurrency: #'BBD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BDT [
	"Bangladeshi taka"
	
	^self asAmountInCurrency: #'BDT' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BGN [
	"Bulgarian lev"
	
	^self asAmountInCurrency: #'BGN' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BHD [
	"Bahraini dinar"
	
	^self asAmountInCurrency: #'BHD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BIF [
	"Burundian franc"
	
	^self asAmountInCurrency: #'BIF' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BMD [
	"Bermudian dollar"
	
	^self asAmountInCurrency: #'BMD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BND [
	"Brunei dollar"
	
	^self asAmountInCurrency: #'BND' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BOB [
	"Boliviano"
	
	^self asAmountInCurrency: #'BOB' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BOV [
	"Bolivian Mvdol (funds code)"
	
	^self asAmountInCurrency: #'BOV' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BRL [
	"Brazilian real"
	
	^self asAmountInCurrency: #'BRL' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BSD [
	"Bahamian dollar"
	
	^self asAmountInCurrency: #'BSD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BTN [
	"Bhutanese ngultrum"
	
	^self asAmountInCurrency: #'BTN' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BWP [
	"Botswana pula"
	
	^self asAmountInCurrency: #'BWP' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BYN [
	"New Belarusian ruble"
	
	^self asAmountInCurrency: #'BYN' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BYR [
	"Belarusian ruble"
	
	^self asAmountInCurrency: #'BYR' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> BZD [
	"Belize dollar"
	
	^self asAmountInCurrency: #'BZD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CAD [
	"Canadian dollar"
	
	^self asAmountInCurrency: #'CAD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CDF [
	"Congolese franc"
	
	^self asAmountInCurrency: #'CDF' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CHE [
	"WIR Euro (complementary currency)"
	
	^self asAmountInCurrency: #'CHE' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CHF [
	"Swiss franc"
	
	^self asAmountInCurrency: #'CHF' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CHW [
	"WIR Franc (complementary currency)"
	
	^self asAmountInCurrency: #'CHW' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CLF [
	"Unidad de Fomento (funds code)"
	
	^self asAmountInCurrency: #'CLF' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CLP [
	"Chilean peso"
	
	^self asAmountInCurrency: #'CLP' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CNY [
	"Chinese yuan"
	
	^self asAmountInCurrency: #'CNY' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> COP [
	"Colombian peso"
	
	^self asAmountInCurrency:#'COP' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> COU [
	"Unidad de Valor Real (UVR) (funds code)"
	
	^self asAmountInCurrency: #'COU' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CRC [
	"Costa Rican colon"
	
	^self asAmountInCurrency: #'CRC' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CUC [
	"Cuban convertible peso"
	
	^self asAmountInCurrency: #'CUC' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CUP [
	"Cuban convertible peso"
	
	^self asAmountInCurrency: #'CUP' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CVE [
	"Cape Verde escudo"
	
	^self asAmountInCurrency: #'CVE' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> CZK [
	"Czech koruna"
	
	^self asAmountInCurrency: #'CZK' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> DJF [
	"Djiboutian franc"
	
	^self asAmountInCurrency: #'DJF' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> DKK [
	"Danish krone"
	
	^self asAmountInCurrency: #'DKK' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> DOP [
	"Dominican peso"
	
	^self asAmountInCurrency: #'DOP' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> DZD [
	"Algerian dinar"
	
	^self asAmountInCurrency: #'DZD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> EGP [
	"Egyptian pound"
	
	^self asAmountInCurrency: #'EGP' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> ERN [
	"Eritrean nakfa"
	
	^self asAmountInCurrency: #'ERN' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> ETB [
	"Ethiopian birr"
	
	^self asAmountInCurrency: #'ETB' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> EUR [
	"Euro"
	
	^self asAmountInCurrency: #'EUR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> FJD [
	"Fiji dollar"
	
	^self asAmountInCurrency: #'FJD' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> FKP [
	"Falkland Islands pound"
	
	^self asAmountInCurrency: #'FKP' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> GBP [
	"Pound sterling"
	
	^self asAmountInCurrency: #'GBP' 
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> GEL [
	"Georgian lari"
	
	^self asAmountInCurrency: #'GEL'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> GHS [
	"Ghanaian cedi"
	
	^self asAmountInCurrency: #'GHS'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> GIP [
	"Gibraltar pound"
	
	^self asAmountInCurrency: #'GIP'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> GMD [
	"Gambian dalasi"
	
	^self asAmountInCurrency: #'GMD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> GNF [
	"Guinean franc"
	
	^self asAmountInCurrency: #'GNF'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> GTQ [
	"Guatemalan quetzal"
	
	^self asAmountInCurrency: #'GTQ'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> GYD [
	"Guyanese dollar"
	
	^self asAmountInCurrency: #'GYD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> HKD [
	"Hong Kong dollar"
	
	^self asAmountInCurrency: #'HKD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> HNL [
	"Honduran lempira"
	
	^self asAmountInCurrency: #'HNL'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> HRK [
	"Croatian kuna"
	
	^self asAmountInCurrency: #'HRK'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> HTG [
	"Haitian gourde"
	
	^self asAmountInCurrency: #'HTG'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> IDR [
	"Indonesian rupiah"
	
	^self asAmountInCurrency: #'IDR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> IDS [
	"Israeli new shekel"
	
	^self asAmountInCurrency: #'IDS'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> INR [
	"Indian rupee"
	
	^self asAmountInCurrency: #'INR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> IQD [
	"Iraqi dinar"
	
	^self asAmountInCurrency: #'IQD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> IRR [
	"Iranian rial"
	
	^self asAmountInCurrency: #'IRR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> ISK [
	"Icelandic króna"
	
	^self asAmountInCurrency: #'ISK'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> JMD [
	"Jamaican dollar"
	
	^self asAmountInCurrency: #'JMD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> JOD [
	"Jordanian dinar"
	
	^self asAmountInCurrency: #'JOD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> JPY [
	"Japanese yen"
	
	^self asAmountInCurrency: #'JPY'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> KES [
	"Kenyan shilling"
	
	^self asAmountInCurrency: #'KES'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> KGS [
	"Kyrgyzstani som"
	
	^self asAmountInCurrency: #'KGS'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> KHR [
	"Cambodian riel"
	
	^self asAmountInCurrency: #'KHR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> KMF [
	"Comoro franc"
	
	^self asAmountInCurrency: #'KMF'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> KPW [
	"North Korean won"
	
	^self asAmountInCurrency: #'KPW'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> KRW [
	"South Korean won"
	
	^self asAmountInCurrency: #'KRW'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> KWD [
	"Kuwaiti dinar"
	
	^self asAmountInCurrency: #'KWD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> KYD [
	"Cayman Islands dollar"
	
	^self asAmountInCurrency: #'KYD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> KZT [
	"Kazakhstani tenge"
	
	^self asAmountInCurrency: #'KZT'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> LAK [
	"Lao kip"
	
	^self asAmountInCurrency: #'LAK'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> LBP [
	"Lebanese pound"
	
	^self asAmountInCurrency: #'LBP'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> LKR [
	"Sri Lankan rupee"
	
	^self asAmountInCurrency: #'LKR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> LRD [
	"Liberian dollar"
	
	^self asAmountInCurrency: #'LRD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> LSL [
	"Liberian dollar"
	
	^self asAmountInCurrency: #'LSL'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> LYD [
	"Libyan dinar"
	
	^self asAmountInCurrency: #'LYD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MAD [
	"Moroccan dirham"
	
	^self asAmountInCurrency: #'MAD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MDL [
	"Moldovan leu"
	
	^self asAmountInCurrency: #'MDL'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MGA [
	"Malagasy ariary"
	
	^self asAmountInCurrency: #'MGA'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MKD [
	"Macedonian denar"
	
	^self asAmountInCurrency: #'MKD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MMK [
	"Myanmar kyat"
	
	^self asAmountInCurrency: #'MMK'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MNT [
	"Mongolian tögrög"
	
	^self asAmountInCurrency: #'MNT'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MOP [
	"Macanese pataca"
	
	^self asAmountInCurrency: #'MOP'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MRO [
	"Mauritanian ouguiya"
	
	^self asAmountInCurrency: #'MRO'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MUR [
	"Mauritian rupee"
	
	^self asAmountInCurrency: #'MUR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MVR [
	"Maldivian rufiyaa"
	
	^self asAmountInCurrency: #'MVR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MWK [
	"Malawian kwacha"
	
	^self asAmountInCurrency: #'MWK'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MXN [
	"Mexican peso"
	
	^self asAmountInCurrency: #'MXN'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MXV [
	"Mexican Unidad de Inversion (UDI) (funds code)"
	
	^self asAmountInCurrency: #'MXV'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MYR [
	"Malaysian ringgit"
	
	^self asAmountInCurrency: #'MYR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> MZN [
	"Mozambican metical"
	
	^self asAmountInCurrency: #'MZN'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> NAD [
	"Namibian dollar"
	
	^self asAmountInCurrency: #'NAD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> NGN [
	"Nigerian naira"
	
	^self asAmountInCurrency: #'NGN'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> NIO [
	"Nicaraguan córdoba"
	
	^self asAmountInCurrency: #'NIO'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> NOK [
	"Norwegian krone"
	
	^self asAmountInCurrency: #'NOK'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> NPR [
	"Nepalese rupee"
	
	^self asAmountInCurrency: #'NPR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> NZD [
	"Nepalese rupee"
	
	^self asAmountInCurrency: #'NZD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> OMR [
	"Omani rial"
	
	^self asAmountInCurrency: #'OMR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> PAB [
	"Panamanian balboa"
	
	^self asAmountInCurrency: #'PAB'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> PEN [
	"Peruvian Sol"
	
	^self asAmountInCurrency: #'PEN'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> PGK [
	"Papua New Guinean kina"
	
	^self asAmountInCurrency: #'PGK'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> PHP [
	"Philippine peso"
	
	^self asAmountInCurrency: #'PHP'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> PKR [
	"Pakistani rupee"
	
	^self asAmountInCurrency: #'PKR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> PLN [
	"Polish złoty"
	
	^self asAmountInCurrency: #'PLN'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> PYG [
	"Paraguayan guaraní"
	
	^self asAmountInCurrency: #'PYG'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> QAR [
	"Qatari riyal"
	
	^self asAmountInCurrency: #'QAR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> RON [
	"Romanian leu"
	
	^self asAmountInCurrency: #'RON'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> RSD [
	"Serbian dinar"
	
	^self asAmountInCurrency: #'RSD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> RUB [
	"Russian ruble"
	
	^self asAmountInCurrency: #'RUB'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> RWF [
	"Rwandan franc"
	
	^self asAmountInCurrency: #'RWF'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SAR [
	"Saudi riyal"
	
	^self asAmountInCurrency: #'SAR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SBD [
	"Solomon Islands dollar"
	
	^self asAmountInCurrency: #'SBD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SCR [
	"Seychelles rupee"
	
	^self asAmountInCurrency: #'SCR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SDG [
	"Sudanese pound"
	
	^self asAmountInCurrency: #'SDG'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SEK [
	"Swedish krona/kronor"
	
	^self asAmountInCurrency: #'SEK'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SGD [
	"Singapore dollar"
	
	^self asAmountInCurrency: #'SGD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SHP [
	"Saint Helena pound"
	
	^self asAmountInCurrency: #'SHP'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SLL [
	"Sierra Leonean leone"
	
	^self asAmountInCurrency: #'SLL'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SOS [
	"Somali shilling"
	
	^self asAmountInCurrency: #'SOS'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SRD [
	"Surinamese dollar"
	
	^self asAmountInCurrency: #'SRD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SSP [
	"South Sudanese pound"
	
	^self asAmountInCurrency: #'SSP'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> STD [
	"São Tomé and Príncipe dobra"
	
	^self asAmountInCurrency: #'STD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SVC [
	"Salvadoran colón"
	
	^self asAmountInCurrency: #'SVC'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SYP [
	"Syrian pound"
	
	^self asAmountInCurrency: #'SYP'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> SZL [
	"Swazi lilangeni"
	
	^self asAmountInCurrency: #'SZL'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> THB [
	"Thai baht"
	
	^self asAmountInCurrency: #'THB'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> TJS [
	"Tajikistani somoni"
	
	^self asAmountInCurrency: #'TJS'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> TMT [
	"Turkmenistani manat"
	
	^self asAmountInCurrency: #'TMT'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> TND [
	"Tunisian dinar"
	
	^self asAmountInCurrency: #'TND'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> TOP [
	"Tongan paʻanga"
	
	^self asAmountInCurrency: #'TOP'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> TRY [
	"Turkish lira"
	
	^self asAmountInCurrency: #'TRY'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> TTD [
	"Trinidad and Tobago dollar"
	
	^self asAmountInCurrency: #'TTD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> TWD [
	"New Taiwan dollar"
	
	^self asAmountInCurrency: #'TWD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> TZS [
	"Tanzanian shilling"
	
	^self asAmountInCurrency: #'TZS'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> UAH [
	"Ukrainian hryvnia"
	
	^self asAmountInCurrency: #'UAH'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> UGX [
	"Ugandan shilling"
	
	^self asAmountInCurrency: #'UGX'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> USD [
	"United States dollar"
	
	^self asAmountInCurrency: #'USD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> USN [
	"United States dollar (next day) (funds code)"
	
	^self asAmountInCurrency: #'USN'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> UYI [
	"Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)"
	
	^self asAmountInCurrency: #'UYI'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> UYU [
	"Uruguayan peso"
	
	^self asAmountInCurrency: #'UYU'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> UZS [
	"Uzbekistan som"
	
	^self asAmountInCurrency: #'UZS'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> VEF [
	"Venezuelan bolívar"
	
	^self asAmountInCurrency: #'VEF'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> VND [
	"Vietnamese dong"
	
	^self asAmountInCurrency: #'VND'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> VUV [
	"Vanuatu vatu"
	
	^self asAmountInCurrency: #'VUV'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> WST [
	"Samoan tala"
	
	^self asAmountInCurrency: #'WST'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XAF [
	"CFA franc BEAC"
	
	^self asAmountInCurrency: #'XAF'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XAG [
	"Silver (one troy ounce)"
	
	^self asAmountInCurrency: #'XAG'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XAU [
	"Gold (one troy ounce)"
	
	^self asAmountInCurrency: #'XAU'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XBA [
	"European Composite Unit (EURCO) (bond market unit)"
	
	^self asAmountInCurrency: #'XBA'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XBB [
	"European Monetary Unit (E.M.U.-6) (bond market unit)"
	
	^self asAmountInCurrency: #'XBB'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XBC [
	"European Unit of Account 9 (E.U.A.-9) (bond market unit)"
	
	^self asAmountInCurrency: #'XBC'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XBD [
	"European Unit of Account 17 (E.U.A.-17) (bond market unit)"
	
	^self asAmountInCurrency: #'XBD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XCD [
	"East Caribbean dollar"
	
	^self asAmountInCurrency: #'XCD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XDR [
	"Special drawing rights"
	
	^self asAmountInCurrency: #'XDR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XOF [
	"CFA franc BCEAO"
	
	^self asAmountInCurrency: #'XOF'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XPD [
	"CFA franc BCEAO"
	
	^self asAmountInCurrency: #'XPD'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XPF [
	"CFP franc (franc Pacifique)"
	
	^self asAmountInCurrency: #'XPF'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XPT [
	"Platinum (one troy ounce)"
	
	^self asAmountInCurrency: #'XPT'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XSU [
	"SUCRE"
	
	^self asAmountInCurrency: #'XSU'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XTS [
	"Code reserved for testing purposes"
	
	^self asAmountInCurrency: #'XTS'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XUA [
	"ADB Unit of Account"
	
	^self asAmountInCurrency: #'XUA'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> XXX [
	"No currency"
	
	^self asAmountInCurrency: #'XXX'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> YER [
	"Yemeni rial"
	
	^self asAmountInCurrency: #'YER'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> ZAR [
	"South African rand"
	
	^self asAmountInCurrency: #'ZAR'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> ZMW [
	"Zambian kwacha"
	
	^self asAmountInCurrency: #'ZMW'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> ZWL [
	"Zimbabwean dollar A/10"
	
	^self asAmountInCurrency: #'ZWL'
]

{ #category : #'*Quant-Core-Currencies-Currencies' }
Number >> asAmountInCurrency: currencyCode [

	^QNTAmount value: (self asScaledDecimal: 2) currencyCode: currencyCode
]
